from . import fleet_service_notification
from . import partner_category
from . import project
from . import project_task
from . import fleet_vehicle
from . import mail_channel
from . import fleet_km_tag
from . import fleet_model_km
from . import fleet_model_horometer
from . import fleet_vehicle_odometer
from . import fleet_log_services
from . import fleet_vehicle_model
from . import stock_production_lot
from . import rental_order_wizard